# Generated by Django 2.2.7 on 2019-11-12 21:14

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCPFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default=backend.models.get_default_filename, max_length=255)),
            ],
        ),
    ]
