# Generated by Django 2.2.7 on 2019-11-11 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcpfile',
            old_name='filename',
            new_name='path',
        ),
    ]
