# Generated by Django 2.2.7 on 2019-11-11 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20191111_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcpfile',
            name='deleted',
        ),
    ]
